### ISSUE TITLE
select stream quality

### ISSUE THREAD

**Issue by ffleischer** [simon-weber/Unofficial-Google-Music-API#287] opened 2014-08-27 17:04 UTC
would it be possible to select the quality of the stream (e.g. low/ medium/ high) like in the android app?

**Comment by thebigmunch** [comment] 2015-03-08 23:53
So, I was looking into this a bit and found some interesting things. No matter what quality setting I set, the bitrate of the streamed mp3 was not affected. All uploaded flac and 320 kbps mp3 streamed at 320 kbps and any uploaded mp3 files less than 320 kbps came out at the uploaded bitrate.

While playing around, I noticed a ``targetkbps`` param in the request URL from the Android app. The values of which made no apparent sense to me. The values for one song (an uploaded FLAC) were as follows:

```
hi - 512
med - 12435
low - 12863

med 2nd run - 11777
low 2nd run - 12877

low 3rd run - 12797
```

So I then tested calling with all these values, still no dice on getting different stream bitrates.

So, I decided to check the streams from the Android app on different settings with Fiddler... same results. Not sure if I'm missing something or doing something stupid, but it doesn't seem that you get  different stream qualities even in the Android app.

It'd be great if someone else did some testing to show that I just did something horribly wrong, or, worse, prove my testing sound.

**Comment by foreverguest** [comment] 2015-03-09 14:39
Using this api in Kodi I consistently have:
- 320kpbs, with params 'opt':'hi', 'net':'mob'
- 160kpbs, with params 'opt':'med', 'net':'mob'
- 128kpbs, with params 'opt':'low', 'net':'mob'

**Comment by thebigmunch** [comment] 2015-03-09 14:58
Ah, I see now that the XBMC plugin has the net set to 'mob' instead of 'wifi' like in gmusicapi, which would likely be the cause of my testing abnormalities. I beat you to the other issue @foreverguest, so feel free to take this one if you wanted since  : P I'm not sure if there's a test to be added to the server_tests for this or not, haven't looked at the streaming tests.

I'll test using 'mob' to stream to confirm, but I'm pretty sure that's the case.

**Comment by foreverguest** [comment] 2015-03-09 16:06
Something like this would be ok?
https://github.com/simon-weber/Unofficial-Google-Music-API/compare/develop...foreverguest:develop

**Comment by simon-weber** [comment] 2015-03-09 16:10
Yeah, that seems pretty reasonable to me. I like the choice to expose hi/med/low rather than eg kbps since it limits the guarantee we're making to users.

**Comment by thebigmunch** [comment] 2015-03-09 16:20
@foreverguest: "One of tree" <-- Typo in docstring.

**Comment by foreverguest** [comment] 2015-03-09 19:08
Oops, typo fixed. Submitted PR #319.

**Comment by simon-weber** [comment] 2015-06-20 21:00
Closed by https://github.com/simon-weber/Unofficial-Google-Music-API/pull/319.

**Closed by simon-weber** 2015-06-20 21:00 UTC
