### ISSUE TITLE
Missing "track" key in result from get_all_user_playlist_contents()

### ISSUE THREAD

**Issue by loneboat** [simon-weber/Unofficial-Google-Music-API#330] opened 2015-05-13 19:03 UTC
Some entries in the playlists returned from get_all_user_playlist_contents() are missing the 'track' key.

Example entries:

With 'track' key:

    {u'kind': u'sj#playlistEntry', u'deleted': False, u'trackId': u'T4hgfop4jtgkcpp2nowvnnmh5ba', u'lastModifiedTimestamp': u'1431479726209000', u'playlistId': u'76f003df-f3f6-44e9-89bc-d01cafe90752', u'clientId': u'62cbbd22-0cbe-45d9-bde8-013a5782885b', u'source': u'2', u'track': {u'albumArtRef': [{u'url': u'http://lh3.ggpht.com/XJCP6N7OSD353Rs6DFqnf6CfJqHA2mQQ9s0qrIl42PFRAzImwSsll9qqAO2iH8szC22JGSmt48E'}, {u'url': u'http://lh3.googleusercontent.com/_OppeGig4fAfeyxdfpFDZCl_F3GSRQspjrVJ6WRQTRQtf85Zf4VLWhr7q3qT1r7eiHpxJJ8K'}], u'artistId': [u'Ap6exarirw2ls3jjrhnf5p2lcvm'], u'composer': u'', u'year': 2013, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Random Access Memories', u'title': u'Beyond', u'albumArtist': u'Daft Punk', u'trackNumber': 9, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'T4hgfop4jtgkcpp2nowvnnmh5ba', u'nid': u'4hgfop4jtgkcpp2nowvnnmh5ba', u'estimatedSize': u'11611978', u'albumId': u'Bpc2cw3xyf7i3ffifugspb3ufti', u'genre': u'Dance/Electronic', u'playCount': 1, u'artistArtRef': [{u'url': u'http://lh3.googleusercontent.com/xXRZQlYwHquj36N8GtDYYYE0-brdAIfms-hlCoqBi2Wc52rWyxdbTlRmDdTavTMQnlk0NN4q3AI'}], u'kind': u'sj#track', u'primaryVideo': {u'kind': u'sj#video', u'id': u'3T0NqvdUiWI', u'thumbnails': [{u'url': u'https://i.ytimg.com/vi/3T0NqvdUiWI/mqdefault.jpg', u'width': 320, u'height': 180}]}, u'artist': u'Daft Punk', u'durationMillis': u'290000'}, u'absolutePosition': u'02168862236389117907', u'creationTimestamp': u'1425429271754529', u'id': u'233e77be-7f44-3ef9-85f4-5fdcfae73789'}

Missing 'track' key:

    {u'kind': u'sj#playlistEntry', u'deleted': False, u'trackId': u'8bd3acf7-c042-3081-af3a-52c60627e8f6', u'lastModifiedTimestamp': u'1431479726209000',u'playlistId': u'76f003df-f3f6-44e9-89bc-d01cafe90752', u'clientId': u'd91b902b-e6bf-4364-92d8-866fe8115356', u'source': u'1', u'absolutePosition': u'02134617043182973943', u'creationTimestamp': u'1422402555107856', u'id': u'ead6e431-eb83-340d-bcb5-492ae12d9ea6'}

**Comment by simon-weber** [comment] 2015-05-13 20:37
This looks like a duplicate of #232.

The tl;dr from https://github.com/simon-weber/Unofficial-Google-Music-API/issues/232#issuecomment-43887144 is that this appears to be a design choice and we'd need to do the matching clientside.

**Closed by simon-weber** 2015-05-13 20:37 UTC
